routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
Route::get('/', function () {
    return view('welcome');
});

Route::get('/', function () {
    return redirect('/blog');
});



*/
use App\Model\Roles;
use App\User;
use App\Model\Article;

use Illuminate\Support\Facades\Auth;
use App\Model\Categories;


Route::get('/', 'BlogController@index');
Route::get('/blog', 'BlogController@blog');
Route::get('blog/{slug}', 'BlogController@showPost');
Route::get('blog/categories/{slug}', 'BlogController@ListCategories');

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::get('/tes', 'HomeController@tes');



Route::get('/blog/lang/{id}', 'BlogController@getLang');
 
             
Route::group(['namespace'=>'admin','middleware'=>'admin','group'=>'Admin'],
function()
{ 

  Route::get('/admin', array('as'=>'admin','uses'=>'DashboardController@index') );
  Route::resource('admin/article','ArticleController');
  Route::get('admin/categories/data',['as' =>'categories.data','uses'=>'CategoriesController@getdata']);
  Route::resource('admin/categories','CategoriesController');
  Route::resource('admin/tags','TagsController');
  
  Route::get('admin/profile/{id}', ['as'=>'profile','uses'=>'ProfileController@index']);
  Route::post('admin/profile', ['as'=>'profile.store','uses'=>'ProfileController@store']);
  
  //log
   Route::get('admin/visitorlog', ['as'=>'visitorlog','uses'=>'VisitorController@index']);

}
);

Route::get('/ok',function(){
	
  $session=\Session::get('lang');

  dd($session);
});

Route::get('level', function() {
    //

		$roles=Roles::all();

		foreach ($roles as $key )
		{
			echo $key->Useradmin;
		}

});

Route::get('leveladmin', function() {
    //

		$user=User::all();

		foreach ($user as $key )
		{
			echo $key->Roles;
		}

});

Route::get('who', function() {
   
  	$artikel=Article::all();

  	foreach ($artikel as $key )
  	{
  		//dd($key).'</br>';

  		dd($key->categoriesArticle);
  	}


});

app/Http/Controllers/Admin/ArticleController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Model\Article;
use Illuminate\Support\Facades\Log;
use App\Model\Article as ArticleModel;
use Illuminate\Support\Facades\Auth;
use App\Http\Requests\ArticleRequest;
use App\Model\Categories as CategoriesModel;
use App\Model\Tags;

class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        Log::info('User showing Menu Article.', ['name' => Auth::user()->name]);
        $article=ArticleModel::orderBy('published_at','desc')->paginate(config('blog.PAGINATE'));
        return view('admin.article.index')->with('article',$article);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        Log::info('User Will Created new Article.', ['name' => Auth::user()->name]);
        $category=CategoriesModel::pluck('name_categories','id');
        $tags=Tags::all();
       
        //return view('admin.article.create')->with('category',$category);
        return view('admin.article.create',compact('category','tags'));


       
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ArticleRequest $request)
    {
       // dd($request->input('tags'));

        
        $db = new ArticleModel($request->all());
        $input=$request->all();
        $db->author_id=Auth::user()->id;
        $db->categories_id=$input['categories_id'];
        $db->hitview=0;
        $db->save();
        $db->tags()->attach($request->input('tags'));
       
        return redirect()->Route('article.index')->with('flash_message','Article Succesfully Save');
        
       
         
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ArticleRequest $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/article/create.blade.php
@extends('layouts.app')
@section('page','New Article')
@section('content')
<div class="row">

    <script type="text/javascript">
         $(".tag").select2();
    </script>

        {!! Form::open(['route'=>'article.store']) !!}

    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
               @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    @if(Session::has('flash_message'))
            <div class="alert alert-success">
                {{ Session::get('flash_message') }}
            </div>
    @endif

    <div class="form-group">
                               
        {!! Form::label('title') !!}
        {!! Form::text('title',null, array('placeholder' => 'Name','class' => 'form-control')) !!}
        

    </div>
       <div class="form-group">
             {!! Form::label('Categories') !!}<br/>
              {!! Form::select('categories_id',$category,array('class'=>'btn btn-primary')) !!}
            </div> 
        <div class="form-group">
             {!! Form::label('Tags') !!}<br/>
              <select name="tags[]" class="form-control tag" multiple="multiple">
                  @foreach ($tags as $tag)
                    <option value="{{ $tag->id}} ">{{$tag->name}}</option>
                  @endforeach
              </select>
        </div> 

     <div class="form-group">
                               
        {!! Form::label('desc') !!}
        {!! Form::textarea('desc',null, array('placeholder' => 'Name','class' => 'form-control','id'=>'desc-ckeditor')) !!}
        <p class="help-block">Example block-level help text here.</p>

    </div>
    <div class="form-group">
                               
        {!! Form::label('Content') !!}
        {!! Form::textarea('content',null, array('placeholder' => 'Name','class' => 'form-control','id'=>'article-ckeditor')) !!}
        <p class="help-block">Example block-level help text here.</p>

    </div>
                       
       
        {!! Form::submit(Lang::get('core.sb_save'),array('class'=>'btn btn-primary')) !!}

        {!! Form::close() !!}

    </div>
 	
</div>


@endsection
@section('scripts')

<script src="/vendor/unisharp/laravel-ckeditor/ckeditor.js"></script>
<script>
        CKEDITOR.replace( 'article-ckeditor' );

</script>


@endsection

resources/views/admin/article/edit.blade.php
@extends('layouts.admin_layout')
@section('page','Edit Categories')

@section('content')
<div class="row">


                                {!! Form::model($detail, [
                        'method' => 'PATCH',
                        'route' => ['categories.update', $detail->id]
                                ]) !!}

                                 @if (count($errors) > 0)
                                <div class="alert bg-danger">
                                    <strong>Whoops!</strong> There were some problems with your input.<br><br>
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif

                            @if(Session::has('flash_message'))
                                    <div class="alert alert-success">
                                        {{ Session::get('flash_message') }}
                                    </div>
                                @endif

                                  <div class="form-group">
                               
                                {!! Form::label('Nama Kategori') !!}
                                {!! Form::text('name_categories', $detail->name_categories, array('placeholder' => 'Name','class' => 'form-control')) !!}
                                <p class="help-block">Example block-level help text here.</p>

                           </div>
                       

                           {!! Form::submit('Simpan',array('class'=>'btn btn-primary')) !!}

                                {!! Form::close() !!}

                         </div>
 	
</div>
@endsection

resources/views/admin/article/index.blade.php
@extends('layouts.admin_layout')
@section('page','Categories')
@section('content')


@if(Session::has('flash_message'))
                <div class="alert bg-success" role="alert"> 
                  <svg class="glyph stroked checkmark"><use xlink:href="#stroked-checkmark"></use></svg> {{ Session::get('flash_message') }}
                  <a href="#" class="pull-right"><span class="glyphicon glyphicon-remove"></span></a>
                 </div>
 @endif

<a href="{{URL('admin/article/create')}}" class="btn btn-primary" >{{Lang::get('core.create')}}</a>
<br/>
<div class="row">
<table class="table" id="dataa"  class="stripe">
		<thead>
			<tr>
				<td>Title </td>
				<td>Content </td>
				<td>Categories </td>
				<td>Author </td>
				<td>{{ Lang::get('core.admin_menu_action')}}
				      
				</td>
				
			</tr>
		</thead>
		<tbody>
			 @foreach($article as $data)
					<tr>
						<td>{{ $data->title }}</td>
						<td>{{ str_limit($data->content,100) }}</td>
						<td>{{ $data->categoriesArticle->name_categories}}</td>
						<td>{{ $data->AuthorCreated->name}}</td>
						
						<td>
							 <a href="{{ route('article.show', $data->id) }}" class="btn btn-info">{{Lang::get('core.btn_view')}}</a>
                        	 <a href="{{ route('article.edit', $data->id) }}" class="btn btn-primary">{{Lang::get('core.btn_edit')}}</a>
                                
                                {!! Form::open([
                                    'method' => 'DELETE',
                                    'route' => ['article.destroy', $data->id]
                                ]) !!}
                                {!! Form::submit(Lang::get('core.btn_remove'), ['class' => 'btn btn-danger']) !!}
                                {!! Form::close() !!}
						</td>
					</tr>
			 @endforeach
		</tbody>
</table>
			{!! $article->links() !!}
</div>
@endsection

resources/views/admin/article/show.blade.php
@extends('layouts.admin_layout')
@section('page','Edit Categories')

@section('content')
<div class="row">


                                {!! Form::model($detail, [
                        'method' => 'PATCH',
                        'route' => ['categories.update', $detail->id]
                                ]) !!}

                                 @if (count($errors) > 0)
                                <div class="alert alert-danger">
                                    <strong>Whoops!</strong> There were some problems with your input.<br><br>
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif

                            @if(Session::has('flash_message'))
                                    <div class="alert alert-success">
                                        {{ Session::get('flash_message') }}
                                    </div>
                                @endif

                                  <div class="form-group">
                               
                                {!! Form::label('Nama Kategori') !!}
                                {!! Form::text('name_categories', $detail->name_categories, array('placeholder' => 'Name','class' => 'form-control')) !!}
                                <p class="help-block">Example block-level help text here.</p>

                           </div>
                       

                           {!! Form::submit('Simpan') !!}

                                {!! Form::close() !!}

                         </div>
 	
</div>
@endsection