routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
Route::get('/', function () {
    return view('welcome');
});

Route::get('/', function () {
    return redirect('/blog');
});



*/
use App\Model\Roles;
use App\User;
use App\Model\Article;

use Illuminate\Support\Facades\Auth;
use App\Model\Categories;


Route::get('/', 'BlogController@index');
Route::get('/blog', 'BlogController@blog');
Route::get('blog/{slug}', 'BlogController@showPost');
Route::get('blog/categories/{slug}', 'BlogController@ListCategories');

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::get('/tes', 'HomeController@tes');



Route::get('/blog/lang/{id}', 'BlogController@getLang');
 
             
Route::group(['namespace'=>'admin','middleware'=>'admin','group'=>'Admin'],
function()
{ 

  Route::get('/admin', array('as'=>'admin','uses'=>'DashboardController@index') );
  Route::resource('admin/article','ArticleController');
  Route::get('admin/categories/data',['as' =>'categories.data','uses'=>'CategoriesController@getdata']);
  Route::resource('admin/categories','CategoriesController');
  Route::resource('admin/tags','TagsController');
  
  Route::get('admin/profile/{id}', ['as'=>'profile','uses'=>'ProfileController@index']);
  Route::post('admin/profile', ['as'=>'profile.store','uses'=>'ProfileController@store']);
  
  //log
   Route::get('admin/visitorlog', ['as'=>'visitorlog','uses'=>'VisitorController@index']);

}
);

Route::get('/ok',function(){
	
  $session=\Session::get('lang');

  dd($session);
});

Route::get('level', function() {
    //

		$roles=Roles::all();

		foreach ($roles as $key )
		{
			echo $key->Useradmin;
		}

});

Route::get('leveladmin', function() {
    //

		$user=User::all();

		foreach ($user as $key )
		{
			echo $key->Roles;
		}

});

Route::get('who', function() {
   
  	$artikel=Article::all();

  	foreach ($artikel as $key )
  	{
  		//dd($key).'</br>';

  		dd($key->categoriesArticle);
  	}


});

app/Http/Controllers/Admin/TagsController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Model\Tags;

class TagsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        

      $tags= Tags::orderBy('name','asc')->paginate(config('blog.PAGINATE'));
      \Log::info('User showing Menu Tags.', ['name' => \Auth::user()->name]);
      return view('admin.tags.index',compact('tags'));


    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.tags.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,array(
            'name'=>'required|min:2|max:15',

        ));
        $tags = new Tags($request->all());
        $tags->name = $request->name;
        $tags->save();


         return redirect()->route('tags.index')->with('flash_message','Tags successful Created');
 
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/tags/create.blade.php
@extends('layouts.admin_layout')
@section('page','Edit Tags')

@section('content')
<div class="row">
        {!! Form::open(['route'=>'tags.store']) !!}

    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
               @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    @if(Session::has('flash_message'))
            <div class="alert alert-success">
                {{ Session::get('flash_message') }}
            </div>
    @endif

    <div class="form-group">
                               
        {!! Form::label('Name Tags') !!}
        {!! Form::text('name',null, array('placeholder' => 'Name','class' => 'form-control')) !!}
        <p class="help-block">Example block-level help text here.</p>

    </div>
    
          

        {!! Form::submit(Lang::get('core.sb_save'),array('class'=>'btn btn-primary')) !!}

        {!! Form::close() !!}

    </div>
 	
</div>
@endsection

resources/views/admin/tags/index.blade.php
@extends('layouts.admin_layout')
@section('page','Tags')
@section('content')


@if(Session::has('flash_message'))
                <div class="alert bg-success" role="alert"> 
                  <svg class="glyph stroked checkmark"><use xlink:href="#stroked-checkmark"></use></svg> {{ Session::get('flash_message') }}
                  <a href="#" class="pull-right"><span class="glyphicon glyphicon-remove"></span></a>
                 </div>
 @endif

<a href="{{URL('admin/tags/create')}}" class="btn btn-primary" >{{Lang::get('core.create')}}</a>
<br/>
<div class="row">
<table class="table" id="dataa"  class="stripe">
		<thead>
			<tr>
				<td>{{ Lang::get('core.admin_categories_name') }} </td>
				<td>{{ Lang::get('core.admin_menu_action')}}
				      
				</td>
				
			</tr>
		</thead>
		<tbody>
			 @foreach($tags as $data)
					<tr>
						<td>{{$data->name}}</td>
						
						<td>
							 <a href="{{ route('categories.show', $data->id) }}" class="btn btn-info">{{Lang::get('core.btn_view')}}</a>
                        	 <a href="{{ route('categories.edit', $data->id) }}" class="btn btn-primary">{{Lang::get('core.btn_edit')}}</a>
                                
                                {!! Form::open([
                                    'method' => 'DELETE',
                                    'route' => ['categories.destroy', $data->id]
                                ]) !!}
                                {!! Form::submit(Lang::get('core.btn_remove'), ['class' => 'btn btn-danger']) !!}
                                {!! Form::close() !!}
						</td>
					</tr>
			 @endforeach
		</tbody>
</table>
			{!! $tags->links() !!}
</div>
@endsection
@push('js')
<script type="text/javascript">
	$(function(){
		$("#data").DataTable({
			 processing: true,
		        serverSide: true,
		        ajax: '{{ url("admin/categories/data") }}',
		        columns: [
		            { data: 'name_categories', name: 'name_categories' },
		            { data: 'lastview', name: 'lastview' },
		            {data: 'action', name: 'action', orderable: false, searchable: false}
		        ]
		});
	});	
</script>

@endpush

resources/views/admin/tags/tes.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    
    <link href="/css/bootstrap.css" rel="stylesheet">
    <link href="/css/select2.css" rel="stylesheet">
    <!-- Scripts -->
    <script>
        window.Laravel = <?php echo json_encode([
            'csrfToken' => csrf_token(),
        ]); ?>
    </script>
    
    <script src="/js/select2.js"></script>
   
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ url('/login') }}">Login</a></li>
                            <li><a href="{{ url('/register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ url('/logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>
        
        <div class="container">
            @yield('content')
        
        </div>
            @yield('scripts')  
    </div>

    <!-- Scripts -->
    <script src="/js/app.js"></script>


</body>
</html>